language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "nightly"
# command to install dependencies
install: "pip install ."
# command to run tests
script: nosetests
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/d1e9925c6d608085f456
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
